/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.PacienteDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author josesanchez
 */
public class InternalBajasPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltasPacientes
     */
    public InternalBajasPacientes() {
        initComponents();
        setSize(700, 350);        
        setResizable(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNombrePacientesBajas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoIDPacienteBajas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoApellidoPacienteBajas = new javax.swing.JTextField();
        btnEliminarPacientesBajas = new javax.swing.JButton();
        btnRestablecerPacientesBajas = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Agregar Pacientes");
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id Paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 90, 20);

        campoNombrePacientesBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombrePacientesBajasActionPerformed(evt);
            }
        });
        getContentPane().add(campoNombrePacientesBajas);
        campoNombrePacientesBajas.setBounds(160, 60, 440, 23);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 60, 70, 20);

        campoIDPacienteBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDPacienteBajasActionPerformed(evt);
            }
        });
        getContentPane().add(campoIDPacienteBajas);
        campoIDPacienteBajas.setBounds(160, 10, 440, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 110, 70, 17);
        getContentPane().add(campoApellidoPacienteBajas);
        campoApellidoPacienteBajas.setBounds(160, 110, 440, 23);

        btnEliminarPacientesBajas.setText("Eliminar");
        btnEliminarPacientesBajas.setToolTipText("");
        btnEliminarPacientesBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPacientesBajasActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarPacientesBajas);
        btnEliminarPacientesBajas.setBounds(400, 180, 170, 50);

        btnRestablecerPacientesBajas.setText("Restablecer");
        getContentPane().add(btnRestablecerPacientesBajas);
        btnRestablecerPacientesBajas.setBounds(190, 180, 170, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombrePacientesBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombrePacientesBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombrePacientesBajasActionPerformed

    private void campoIDPacienteBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDPacienteBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDPacienteBajasActionPerformed

    private void btnEliminarPacientesBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPacientesBajasActionPerformed
        // TODO add your handling code here:

        int id = Integer.parseInt(campoIDPacienteBajas.getText().trim());
    
        
        boolean ok = PacienteDAO.getInstancia().eliminarPaciente(id); 
        
        if(ok){
            JOptionPane.showMessageDialog(this, "Paciente eliminado correctamente.");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el paciente");
        }
    }//GEN-LAST:event_btnEliminarPacientesBajasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarPacientesBajas;
    private javax.swing.JButton btnRestablecerPacientesBajas;
    private javax.swing.JTextField campoApellidoPacienteBajas;
    private javax.swing.JTextField campoIDPacienteBajas;
    private javax.swing.JTextField campoNombrePacientesBajas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    
}
