package vista;

import controlador.MedicoDAO;
import javax.swing.JOptionPane;
import modelo.Medico;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class InternalCambiosMedicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltasMedicos
     */
    public InternalCambiosMedicos() {
        initComponents();
        setSize(700, 350);        
        setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoIdMedicoCambios = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoNombreMedicoCambios = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoApellidoMedicoCambios = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboMedicoDepartamentoCambios = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        campoDireccionMedicoCambios = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoTelefonoMedicoCambios = new javax.swing.JTextField();
        btnModificarMedicoCambios = new javax.swing.JButton();
        btnRestablecerMedicoCambios = new javax.swing.JButton();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 700, 350));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setPreferredSize(new java.awt.Dimension(700, 350));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(110, 46, 46));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id del Médico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 90, 20);

        campoIdMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(campoIdMedicoCambios);
        campoIdMedicoCambios.setBounds(150, 20, 360, 20);

        jLabel2.setBackground(new java.awt.Color(110, 46, 46));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 60, 60, 20);

        campoNombreMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(campoNombreMedicoCambios);
        campoNombreMedicoCambios.setBounds(150, 60, 360, 20);

        jLabel3.setBackground(new java.awt.Color(110, 46, 46));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 100, 60, 20);

        campoApellidoMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(campoApellidoMedicoCambios);
        campoApellidoMedicoCambios.setBounds(150, 100, 360, 20);

        jLabel4.setBackground(new java.awt.Color(110, 46, 46));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número del Departamento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 180, 20);

        comboMedicoDepartamentoCambios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));
        comboMedicoDepartamentoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicoDepartamentoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(comboMedicoDepartamentoCambios);
        comboMedicoDepartamentoCambios.setBounds(230, 140, 72, 23);

        jLabel5.setBackground(new java.awt.Color(110, 46, 46));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 180, 70, 20);

        campoDireccionMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(campoDireccionMedicoCambios);
        campoDireccionMedicoCambios.setBounds(150, 180, 460, 20);

        jLabel6.setBackground(new java.awt.Color(110, 46, 46));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefóno");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 220, 70, 20);

        campoTelefonoMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefonoMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(campoTelefonoMedicoCambios);
        campoTelefonoMedicoCambios.setBounds(150, 220, 460, 20);

        btnModificarMedicoCambios.setBackground(new java.awt.Color(120, 0, 0));
        btnModificarMedicoCambios.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/ProjectoFinalWM_mock/src/main/resources/Imagenes/modify.png")); // NOI18N
        btnModificarMedicoCambios.setToolTipText("Modificar");
        btnModificarMedicoCambios.setBorder(null);
        btnModificarMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarMedicoCambios);
        btnModificarMedicoCambios.setBounds(560, 20, 50, 50);

        btnRestablecerMedicoCambios.setBackground(new java.awt.Color(120, 0, 0));
        btnRestablecerMedicoCambios.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/WellmeadowsHospitalProyectoFinal/src/main/resources/Imagenes/clean.png")); // NOI18N
        btnRestablecerMedicoCambios.setToolTipText("Restablecer");
        btnRestablecerMedicoCambios.setBorder(null);
        btnRestablecerMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestablecerMedicoCambios);
        btnRestablecerMedicoCambios.setBounds(560, 100, 50, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdMedicoCambiosActionPerformed

    private void campoNombreMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreMedicoCambiosActionPerformed

    private void campoApellidoMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoMedicoCambiosActionPerformed

    private void comboMedicoDepartamentoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicoDepartamentoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMedicoDepartamentoCambiosActionPerformed

    private void campoDireccionMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionMedicoCambiosActionPerformed

    private void campoTelefonoMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefonoMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoMedicoCambiosActionPerformed

    private void btnModificarMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMedicoCambiosActionPerformed
        // TODO add your handling code here:
        
        Medico m = new Medico(); 
        
        m.setIdMedico(Integer.parseInt(campoIdMedicoCambios.getText().trim()));
        m.setNombre(campoNombreMedicoCambios.getText().trim()); 
        m.setApellido(campoApellidoMedicoCambios.getText().trim()); 
        m.setNumeroDepartamento(Integer.parseInt(comboMedicoDepartamentoCambios.getSelectedItem().toString()));
        m.setDireccion(campoDireccionMedicoCambios.getText().trim()); 
        m.setTelefono(campoTelefonoMedicoCambios.getText().trim());
        
        boolean actualizado = MedicoDAO.getInstancia().modiifcarMedico(m);
        if(actualizado){
            JOptionPane.showMessageDialog(this, "Datos del médico fueron modificados exitosamente");
        }else{
            JOptionPane.showMessageDialog(this, "Datos no se pudieron modificar, verifique que el ID sea válido.");
        }
    }//GEN-LAST:event_btnModificarMedicoCambiosActionPerformed

    private void btnRestablecerMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestablecerMedicoCambiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarMedicoCambios;
    private javax.swing.JButton btnRestablecerMedicoCambios;
    private javax.swing.JTextField campoApellidoMedicoCambios;
    private javax.swing.JTextField campoDireccionMedicoCambios;
    private javax.swing.JTextField campoIdMedicoCambios;
    private javax.swing.JTextField campoNombreMedicoCambios;
    private javax.swing.JTextField campoTelefonoMedicoCambios;
    private javax.swing.JComboBox<String> comboMedicoDepartamentoCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
