/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.PacienteDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author josesanchez
 */
public class InternalBajasPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltasPacientes
     */
    public InternalBajasPacientes() {
        initComponents();
        setSize(700, 350);        
        setResizable(false);
        
        
        
    }

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoIDPacienteBajas = new javax.swing.JTextField();
        btnEliminarPacientesBajas = new javax.swing.JButton();
        btnRestablecerPacientesBajas = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Eliminar Pacientes");
        setToolTipText("");
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id Paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 80, 90, 20);

        campoIDPacienteBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDPacienteBajasActionPerformed(evt);
            }
        });
        getContentPane().add(campoIDPacienteBajas);
        campoIDPacienteBajas.setBounds(180, 80, 440, 23);

        btnEliminarPacientesBajas.setText("Eliminar");
        btnEliminarPacientesBajas.setToolTipText("");
        btnEliminarPacientesBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPacientesBajasActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarPacientesBajas);
        btnEliminarPacientesBajas.setBounds(100, 130, 250, 50);

        btnRestablecerPacientesBajas.setText("Restablecer");
        getContentPane().add(btnRestablecerPacientesBajas);
        btnRestablecerPacientesBajas.setBounds(370, 130, 250, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIDPacienteBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDPacienteBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDPacienteBajasActionPerformed

    private void btnEliminarPacientesBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPacientesBajasActionPerformed
        // TODO add your handling code here:

        int id = Integer.parseInt(campoIDPacienteBajas.getText().trim());
    
        
        boolean ok = PacienteDAO.getInstancia().eliminarPaciente(id); 
        
        if(ok){
            JOptionPane.showMessageDialog(this, "Paciente eliminado correctamente.");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el paciente, verifique el ID");
        }
    }//GEN-LAST:event_btnEliminarPacientesBajasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarPacientesBajas;
    private javax.swing.JButton btnRestablecerPacientesBajas;
    private javax.swing.JTextField campoIDPacienteBajas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
}
