package vista;

import controlador.MedicoDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Medico;
import modelo.ResultSetTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class InternalCambiosMedicos extends javax.swing.JInternalFrame {
    private ResultSetTableModel modelo;
    private String driver = "org.postgresql.Driver";
    private String url = "jdbc:postgresql://localhost:5432/wellmeadows_hospital";
    
    
    /**
     * Creates new form InternalAltasMedicos
     */
    public InternalCambiosMedicos() {
        initComponents();
        setSize(700, 700);        
        setResizable(false);
        
        campoIdMedicoCambios.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent e){
            actualizarEstadoCampos();
        }
    });
        actualizarEstadoCampos();
        cargarTodosLosMedicos(tablaCambiosMedicos);
        
    }
    
    
    
    private void cargarTodosLosMedicos(javax.swing.JTable tablaMedicos) {
        try {
            String sql = "SELECT id_medico, nombre, apellido, numero_departamento, direccion, telefono FROM medicos_cabecera";
            modelo = new ResultSetTableModel(driver, url, sql);
            tablaMedicos.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
  
    
    
    
    private void restablecerCampos() {
        try {
       
            campoIdMedicoCambios.setText("");
            campoNombreMedicoCambios.setText("");
            campoApellidoMedicoCambios.setText("");
            campoDireccionMedicoCambios.setText("");
            campoTelefonoMedicoCambios.setText("");
            comboMedicoDepartamentoCambios.setSelectedIndex(0);
            cargarTodosLosMedicos(tablaCambiosMedicos);
            actualizarEstadoCampos();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }


    private void actualizarEstadoCampos() {

        boolean habilitar = !campoIdMedicoCambios.getText().trim().isEmpty();

        campoNombreMedicoCambios.setEnabled(habilitar);
        campoApellidoMedicoCambios.setEnabled(habilitar);
        comboMedicoDepartamentoCambios.setEnabled(habilitar);
        campoDireccionMedicoCambios.setEnabled(habilitar);
        campoTelefonoMedicoCambios.setEnabled(habilitar);
        btnModificarMedicoCambios.setEnabled(habilitar);
    }
    
    
    public void resfrescarTabla(){
        cargarTodosLosMedicos(tablaCambiosMedicos);
    }
    
    
    public void soloNumeros(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != '\b') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten números!");
        }
    }

    public void soloLetras(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !Character.isWhitespace(c) && c != '\b') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten letras.");
        }
    }
    
    public void limitarCaracteres(java.awt.event.KeyEvent evt, javax.swing.JTextField campo, int max) {
        if (campo.getText().length() >= max) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Máximo permitido: " + max + " caracteres.");
        }
    }
    
    public void limitarSoloDiez(javax.swing.JTextField campo, java.awt.event.KeyEvent evt) {
        if (campo.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "10 digitos para el telefono, no mas, no menos!");
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoIdMedicoCambios = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoNombreMedicoCambios = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoApellidoMedicoCambios = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboMedicoDepartamentoCambios = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        campoDireccionMedicoCambios = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoTelefonoMedicoCambios = new javax.swing.JTextField();
        btnModificarMedicoCambios = new javax.swing.JButton();
        btnRestablecerMedicoCambios = new javax.swing.JButton();
        jScrollMedicos = new javax.swing.JScrollPane();
        tablaCambiosMedicos = new javax.swing.JTable();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Modificar Medicos");
        setBounds(new java.awt.Rectangle(0, 0, 700, 350));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setPreferredSize(new java.awt.Dimension(700, 350));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(110, 46, 46));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id del Médico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 90, 20);

        campoIdMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdMedicoCambiosActionPerformed(evt);
            }
        });
        campoIdMedicoCambios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIdMedicoCambiosKeyTyped(evt);
            }
        });
        getContentPane().add(campoIdMedicoCambios);
        campoIdMedicoCambios.setBounds(150, 20, 360, 20);

        jLabel2.setBackground(new java.awt.Color(110, 46, 46));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 60, 60, 20);

        campoNombreMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreMedicoCambiosActionPerformed(evt);
            }
        });
        campoNombreMedicoCambios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNombreMedicoCambiosKeyTyped(evt);
            }
        });
        getContentPane().add(campoNombreMedicoCambios);
        campoNombreMedicoCambios.setBounds(150, 60, 360, 20);

        jLabel3.setBackground(new java.awt.Color(110, 46, 46));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 100, 60, 20);

        campoApellidoMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoMedicoCambiosActionPerformed(evt);
            }
        });
        campoApellidoMedicoCambios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoApellidoMedicoCambiosKeyTyped(evt);
            }
        });
        getContentPane().add(campoApellidoMedicoCambios);
        campoApellidoMedicoCambios.setBounds(150, 100, 360, 20);

        jLabel4.setBackground(new java.awt.Color(110, 46, 46));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número del Departamento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 180, 20);

        comboMedicoDepartamentoCambios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));
        comboMedicoDepartamentoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicoDepartamentoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(comboMedicoDepartamentoCambios);
        comboMedicoDepartamentoCambios.setBounds(230, 140, 72, 23);

        jLabel5.setBackground(new java.awt.Color(110, 46, 46));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 180, 70, 20);

        campoDireccionMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionMedicoCambiosActionPerformed(evt);
            }
        });
        campoDireccionMedicoCambios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDireccionMedicoCambiosKeyTyped(evt);
            }
        });
        getContentPane().add(campoDireccionMedicoCambios);
        campoDireccionMedicoCambios.setBounds(150, 180, 460, 20);

        jLabel6.setBackground(new java.awt.Color(110, 46, 46));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefóno");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 220, 70, 20);

        campoTelefonoMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefonoMedicoCambiosActionPerformed(evt);
            }
        });
        campoTelefonoMedicoCambios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTelefonoMedicoCambiosKeyTyped(evt);
            }
        });
        getContentPane().add(campoTelefonoMedicoCambios);
        campoTelefonoMedicoCambios.setBounds(150, 220, 460, 20);

        btnModificarMedicoCambios.setText("Modificar");
        btnModificarMedicoCambios.setToolTipText("Hace los cambios");
        btnModificarMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarMedicoCambios);
        btnModificarMedicoCambios.setBounds(550, 40, 120, 40);

        btnRestablecerMedicoCambios.setText("Restablecer");
        btnRestablecerMedicoCambios.setToolTipText("Limpia los campos");
        btnRestablecerMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestablecerMedicoCambios);
        btnRestablecerMedicoCambios.setBounds(550, 100, 120, 40);

        jScrollMedicos.setBackground(new java.awt.Color(51, 0, 0));
        jScrollMedicos.setBorder(null);
        jScrollMedicos.setForeground(new java.awt.Color(51, 51, 51));

        tablaCambiosMedicos.setBackground(new java.awt.Color(100, 0, 0));
        tablaCambiosMedicos.setForeground(new java.awt.Color(255, 255, 255));
        tablaCambiosMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Médico", "Nombre", "Apellido", "Departamento", "Dirección", "Teléfono"
            }
        ));
        jScrollMedicos.setViewportView(tablaCambiosMedicos);

        getContentPane().add(jScrollMedicos);
        jScrollMedicos.setBounds(30, 290, 610, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdMedicoCambiosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoIdMedicoCambiosActionPerformed

    private void campoNombreMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreMedicoCambiosActionPerformed

    private void campoApellidoMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoMedicoCambiosActionPerformed

    private void comboMedicoDepartamentoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicoDepartamentoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMedicoDepartamentoCambiosActionPerformed

    private void campoDireccionMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionMedicoCambiosActionPerformed

    private void campoTelefonoMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefonoMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoMedicoCambiosActionPerformed

    private void btnModificarMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMedicoCambiosActionPerformed
        // TODO add your handling code here:
        if (campoIdMedicoCambios.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo ID no puede estar vacío");
            return;
        }
            if (campoNombreMedicoCambios.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tiene que tener nombre.");
            return;
        }
        if (campoApellidoMedicoCambios.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tiene que tener apellido");
            return;
        }
        if (comboMedicoDepartamentoCambios.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un departamento");
            return;
        }
        if (campoDireccionMedicoCambios.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una dirección");
            return;
        }
        if (campoTelefonoMedicoCambios.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El telefono no puede dejarse vacio!");
            
            return;
        }

    // Valida que ID sea número
    try {
        Integer.parseInt(campoIdMedicoCambios.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.");
        return;
    }

    // Valida que número de departamento sea un número
    try {
        Integer.parseInt(comboMedicoDepartamentoCambios.getSelectedItem().toString());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El departamento debe ser un número válido.");
        return;
    }
        
        
        Medico m = new Medico(); 
        
        m.setIdMedico(Integer.parseInt(campoIdMedicoCambios.getText().trim()));
        m.setNombre(campoNombreMedicoCambios.getText().trim()); 
        m.setApellido(campoApellidoMedicoCambios.getText().trim()); 
        m.setNumeroDepartamento(Integer.parseInt(comboMedicoDepartamentoCambios.getSelectedItem().toString()));
        m.setDireccion(campoDireccionMedicoCambios.getText().trim()); 
        m.setTelefono(campoTelefonoMedicoCambios.getText().trim());
        
        boolean actualizado = MedicoDAO.getInstancia().modiifcarMedico(m);
        if(actualizado){
            JOptionPane.showMessageDialog(this, "Datos del médico fueron modificados exitosamente");
            restablecerCampos();
            cargarTodosLosMedicos(tablaCambiosMedicos);
        }else{
            JOptionPane.showMessageDialog(this, "Datos no se pudieron modificar, verifique que el ID sea válido.");
        }
    }//GEN-LAST:event_btnModificarMedicoCambiosActionPerformed

    private void btnRestablecerMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedicoCambiosActionPerformed
        // TODO add your handling code here:
        restablecerCampos();
        
    }//GEN-LAST:event_btnRestablecerMedicoCambiosActionPerformed

    private void campoIdMedicoCambiosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdMedicoCambiosKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_campoIdMedicoCambiosKeyTyped

    private void campoNombreMedicoCambiosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreMedicoCambiosKeyTyped
        // TODO add your handling code here:
        soloLetras(evt);
        limitarCaracteres(evt, campoNombreMedicoCambios, 45);
        
    }//GEN-LAST:event_campoNombreMedicoCambiosKeyTyped

    private void campoApellidoMedicoCambiosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoApellidoMedicoCambiosKeyTyped
        // TODO add your handling code here:
        soloLetras(evt);
        limitarCaracteres(evt, campoApellidoMedicoCambios, 45);
    }//GEN-LAST:event_campoApellidoMedicoCambiosKeyTyped

    private void campoDireccionMedicoCambiosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDireccionMedicoCambiosKeyTyped
        // TODO add your handling code here:
        limitarCaracteres(evt, campoDireccionMedicoCambios, 45);
    }//GEN-LAST:event_campoDireccionMedicoCambiosKeyTyped

    private void campoTelefonoMedicoCambiosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTelefonoMedicoCambiosKeyTyped
        // TODO add your handling code here:
        
        soloNumeros(evt);
        limitarSoloDiez(campoTelefonoMedicoCambios, evt);
    }//GEN-LAST:event_campoTelefonoMedicoCambiosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarMedicoCambios;
    private javax.swing.JButton btnRestablecerMedicoCambios;
    private javax.swing.JTextField campoApellidoMedicoCambios;
    private javax.swing.JTextField campoDireccionMedicoCambios;
    private javax.swing.JTextField campoIdMedicoCambios;
    private javax.swing.JTextField campoNombreMedicoCambios;
    private javax.swing.JTextField campoTelefonoMedicoCambios;
    private javax.swing.JComboBox<String> comboMedicoDepartamentoCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollMedicos;
    private javax.swing.JTable tablaCambiosMedicos;
    // End of variables declaration//GEN-END:variables
}
