package vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class InternalCambiosMedicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltasMedicos
     */
    public InternalCambiosMedicos() {
        initComponents();
        setSize(700, 350);        
        setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoIdMedicoAltas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoNombreMedicoAltas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoApellidoMedicoAltas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboMedicoDepartamentoAtlas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        campoDireccionMedicoAltas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoDireccionMedicoAltas1 = new javax.swing.JTextField();
        btnModificarMedicoCambios = new javax.swing.JButton();
        btnRestablecerMedicoCambios = new javax.swing.JButton();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 700, 350));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setPreferredSize(new java.awt.Dimension(700, 350));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(110, 46, 46));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id del Médico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 90, 20);

        campoIdMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(campoIdMedicoAltas);
        campoIdMedicoAltas.setBounds(150, 20, 360, 20);

        jLabel2.setBackground(new java.awt.Color(110, 46, 46));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 60, 60, 20);

        campoNombreMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(campoNombreMedicoAltas);
        campoNombreMedicoAltas.setBounds(150, 60, 360, 20);

        jLabel3.setBackground(new java.awt.Color(110, 46, 46));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 100, 60, 20);

        campoApellidoMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(campoApellidoMedicoAltas);
        campoApellidoMedicoAltas.setBounds(150, 100, 360, 20);

        jLabel4.setBackground(new java.awt.Color(110, 46, 46));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número del Departamento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 180, 20);

        comboMedicoDepartamentoAtlas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));
        comboMedicoDepartamentoAtlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicoDepartamentoAtlasActionPerformed(evt);
            }
        });
        getContentPane().add(comboMedicoDepartamentoAtlas);
        comboMedicoDepartamentoAtlas.setBounds(230, 140, 72, 23);

        jLabel5.setBackground(new java.awt.Color(110, 46, 46));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 180, 70, 20);

        campoDireccionMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(campoDireccionMedicoAltas);
        campoDireccionMedicoAltas.setBounds(150, 180, 460, 20);

        jLabel6.setBackground(new java.awt.Color(110, 46, 46));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefóno");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 220, 70, 20);

        campoDireccionMedicoAltas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionMedicoAltas1ActionPerformed(evt);
            }
        });
        getContentPane().add(campoDireccionMedicoAltas1);
        campoDireccionMedicoAltas1.setBounds(150, 220, 460, 20);

        btnModificarMedicoCambios.setBackground(new java.awt.Color(120, 0, 0));
        btnModificarMedicoCambios.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/ProjectoFinalWM_mock/src/main/resources/Imagenes/modify.png")); // NOI18N
        btnModificarMedicoCambios.setToolTipText("Modificar");
        btnModificarMedicoCambios.setBorder(null);
        btnModificarMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarMedicoCambios);
        btnModificarMedicoCambios.setBounds(560, 20, 50, 50);

        btnRestablecerMedicoCambios.setBackground(new java.awt.Color(120, 0, 0));
        btnRestablecerMedicoCambios.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/WellmeadowsHospitalProyectoFinal/src/main/resources/Imagenes/clean.png")); // NOI18N
        btnRestablecerMedicoCambios.setToolTipText("Restablecer");
        btnRestablecerMedicoCambios.setBorder(null);
        btnRestablecerMedicoCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedicoCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestablecerMedicoCambios);
        btnRestablecerMedicoCambios.setBounds(560, 100, 50, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdMedicoAltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdMedicoAltasActionPerformed

    private void campoNombreMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreMedicoAltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreMedicoAltasActionPerformed

    private void campoApellidoMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoMedicoAltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoMedicoAltasActionPerformed

    private void comboMedicoDepartamentoAtlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicoDepartamentoAtlasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMedicoDepartamentoAtlasActionPerformed

    private void campoDireccionMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionMedicoAltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionMedicoAltasActionPerformed

    private void campoDireccionMedicoAltas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionMedicoAltas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionMedicoAltas1ActionPerformed

    private void btnModificarMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMedicoCambiosActionPerformed

    private void btnRestablecerMedicoCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedicoCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestablecerMedicoCambiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarMedicoCambios;
    private javax.swing.JButton btnRestablecerMedicoCambios;
    private javax.swing.JTextField campoApellidoMedicoAltas;
    private javax.swing.JTextField campoDireccionMedicoAltas;
    private javax.swing.JTextField campoDireccionMedicoAltas1;
    private javax.swing.JTextField campoIdMedicoAltas;
    private javax.swing.JTextField campoNombreMedicoAltas;
    private javax.swing.JComboBox<String> comboMedicoDepartamentoAtlas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
