/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import javax.swing.Timer;
import modelo.ResultSetTableModel;

/**
 *
 * @author josesanchez
 */
public class InternalTabla2 extends javax.swing.JInternalFrame {
    private final String driver = "org.postgresql.Driver";
    private final String url = "jdbc:postgresql://localhost:5432/wellmeadows_hospital";
    /**
     * Creates new form internalMedicos
     */
    public InternalTabla2() {
   
        
        initComponents();
        setSize(700, 500);        
        setResizable(false);
         
        cargarVista();
        
        
    }
    
    
    public void cargarVista(){
        try { 
            String consulta = "Select * FROM medicos_historial"; 
            ResultSetTableModel modelo = new ResultSetTableModel(driver, url, consulta);
            tablaVista.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error, no se cargo la vista correctamente");
            e.printStackTrace();
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        tablaVista = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Vista 2");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setNormalBounds(new java.awt.Rectangle(0, 0, 700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setSize(new java.awt.Dimension(700, 700));
        setVisible(true);
        getContentPane().setLayout(null);

        scroll.setBackground(new java.awt.Color(51, 0, 0));
        scroll.setBorder(null);
        scroll.setForeground(new java.awt.Color(51, 51, 51));

        tablaVista.setBackground(new java.awt.Color(100, 0, 0));
        tablaVista.setForeground(new java.awt.Color(255, 255, 255));
        tablaVista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Médico", "Apellido (médico)", "Id paciente", "Nombre", "Apellido"
            }
        ));
        scroll.setViewportView(tablaVista);

        getContentPane().add(scroll);
        scroll.setBounds(30, 90, 610, 310);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Historial de Médicos Eliminados");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 17, 630, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tablaVista;
    // End of variables declaration//GEN-END:variables
}
