package vista;

import controlador.MedicoDAO;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class InternalBajasMedicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltasMedicos
     */
    public InternalBajasMedicos() {
        initComponents();
        setSize(700, 350);        
        setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        campoIdMedicoBajas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoNombreMedicoBajas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoApellidoMedicosBajas = new javax.swing.JTextField();
        btnElminarMedicoAltas = new javax.swing.JButton();
        btnRestablecerMedicosBajas = new javax.swing.JButton();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 700, 350));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setPreferredSize(new java.awt.Dimension(700, 350));
        getContentPane().setLayout(null);

        jLabel8.setBackground(new java.awt.Color(110, 46, 46));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id del Médico");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 30, 90, 20);

        campoIdMedicoBajas.setToolTipText("Campo para eliminar.");
        campoIdMedicoBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdMedicoBajasActionPerformed(evt);
            }
        });
        getContentPane().add(campoIdMedicoBajas);
        campoIdMedicoBajas.setBounds(160, 30, 360, 20);

        jLabel9.setBackground(new java.awt.Color(110, 46, 46));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre (Búsqueda)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 70, 130, 20);

        campoNombreMedicoBajas.setToolTipText("Campo para buscar.");
        campoNombreMedicoBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreMedicoBajasActionPerformed(evt);
            }
        });
        getContentPane().add(campoNombreMedicoBajas);
        campoNombreMedicoBajas.setBounds(160, 70, 360, 20);

        jLabel10.setBackground(new java.awt.Color(110, 46, 46));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Apellido (Búsqueda)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 110, 130, 20);

        campoApellidoMedicosBajas.setToolTipText("Campo para buscar. ");
        campoApellidoMedicosBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoMedicosBajasActionPerformed(evt);
            }
        });
        getContentPane().add(campoApellidoMedicosBajas);
        campoApellidoMedicosBajas.setBounds(160, 110, 360, 20);

        btnElminarMedicoAltas.setBackground(new java.awt.Color(91, 4, 4));
        btnElminarMedicoAltas.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/WellmeadowsHospitalProyectoFinal/src/main/resources/Imagenes/delete.png")); // NOI18N
        btnElminarMedicoAltas.setToolTipText("Eliminar");
        btnElminarMedicoAltas.setBorder(null);
        btnElminarMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElminarMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(btnElminarMedicoAltas);
        btnElminarMedicoAltas.setBounds(410, 180, 40, 50);

        btnRestablecerMedicosBajas.setBackground(new java.awt.Color(91, 4, 4));
        btnRestablecerMedicosBajas.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/WellmeadowsHospitalProyectoFinal/src/main/resources/Imagenes/clean.png")); // NOI18N
        btnRestablecerMedicosBajas.setToolTipText("Restablecer");
        btnRestablecerMedicosBajas.setBorder(null);
        btnRestablecerMedicosBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedicosBajasActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestablecerMedicosBajas);
        btnRestablecerMedicosBajas.setBounds(490, 180, 40, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdMedicoBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdMedicoBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdMedicoBajasActionPerformed

    private void campoNombreMedicoBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreMedicoBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreMedicoBajasActionPerformed

    private void campoApellidoMedicosBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoMedicosBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoMedicosBajasActionPerformed

    private void btnElminarMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElminarMedicoAltasActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(campoIdMedicoBajas.getText().trim()); 
        
        boolean eliminado = MedicoDAO.getInstancia().eliminarMedico(id); 
        
        if(eliminado){
            JOptionPane.showMessageDialog(this, "Médico se eliminó exitosamente.");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo eliminar al doc. Favor de Verificar el ID!");
        }
        
    }//GEN-LAST:event_btnElminarMedicoAltasActionPerformed

    private void btnRestablecerMedicosBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedicosBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestablecerMedicosBajasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElminarMedicoAltas;
    private javax.swing.JButton btnRestablecerMedicosBajas;
    private javax.swing.JTextField campoApellidoMedicosBajas;
    private javax.swing.JTextField campoIdMedicoBajas;
    private javax.swing.JTextField campoNombreMedicoBajas;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
