/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.JButton;

import javax.swing.Timer;

/**
 *
 * @author josesanchez
 */
public class InternalPacientes extends javax.swing.JInternalFrame {

    private InternalAltasPacientes IFAltasPacientes;
    private InternalBajasPacientes IFBajasPacientes;
    private InternalCambiosPacientes IFCambiosPacientes;
    private InternalConsultasPacientes IFConsultasPacientes;
    
    
    public InternalPacientes(InternalAltasPacientes altasPacientes, InternalBajasPacientes bajasPacientes, InternalCambiosPacientes cambiosPacientes, InternalConsultasPacientes consultasPacientes) {
        this.IFAltasPacientes = altasPacientes;
        this.IFBajasPacientes = bajasPacientes;
        this.IFCambiosPacientes = cambiosPacientes; 
        this.IFConsultasPacientes = consultasPacientes; 
        
        initComponents();
        setSize(700, 700);        
        setResizable(false);
      
        
        
        prepararBoton(btnAltasPaciente);
        prepararBoton(btnBajasPacientes);
        prepararBoton(btnConsultasPacientes);
        prepararBoton(btnCambiosPacientes);
        
        
        
    }
    
    
//============ METODOS DISENO BOTONES *START* ================ 
private void hacerClickOscuro(JButton boton) {

    // Color original guardado en una variable local
    Color original = boton.getBackground();

    // Color más oscuro
    Color oscuro = original.darker();

    boton.setBackground(oscuro);

    // Regresar al color original después de 150 ms
    Timer t = new Timer(150, e -> {
        boton.setBackground(original);
    });

    t.setRepeats(false);
    t.start();
}

private void prepararBoton(JButton boton) {
    boton.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    boton.setContentAreaFilled(true);
    boton.setOpaque(true);
    boton.setBorderPainted(false);
}
//=========== METODOS DISENO BOTONES *END* ============= 
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCambiosPacientes = new javax.swing.JButton();
        btnAltasPaciente = new javax.swing.JButton();
        btnBajasPacientes = new javax.swing.JButton();
        btnConsultasPacientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Pacientes");
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setNormalBounds(new java.awt.Rectangle(0, 0, 700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setSize(new java.awt.Dimension(700, 700));
        setVisible(true);
        getContentPane().setLayout(null);

        btnCambiosPacientes.setBackground(new java.awt.Color(100, 0, 0));
        btnCambiosPacientes.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCambiosPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiosPacientes.setText("Modificar");
        btnCambiosPacientes.setBorder(null);
        btnCambiosPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiosPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiosPacientes);
        btnCambiosPacientes.setBounds(50, 310, 270, 100);

        btnAltasPaciente.setBackground(new java.awt.Color(100, 0, 0));
        btnAltasPaciente.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAltasPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnAltasPaciente.setText("Agregar");
        btnAltasPaciente.setBorder(null);
        btnAltasPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltasPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltasPaciente);
        btnAltasPaciente.setBounds(50, 190, 270, 100);

        btnBajasPacientes.setBackground(new java.awt.Color(100, 0, 0));
        btnBajasPacientes.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnBajasPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btnBajasPacientes.setText("Eliminar");
        btnBajasPacientes.setBorder(null);
        btnBajasPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajasPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnBajasPacientes);
        btnBajasPacientes.setBounds(340, 310, 280, 100);

        btnConsultasPacientes.setBackground(new java.awt.Color(100, 0, 0));
        btnConsultasPacientes.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnConsultasPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultasPacientes.setText("Consultar");
        btnConsultasPacientes.setBorder(null);
        btnConsultasPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultasPacientes);
        btnConsultasPacientes.setBounds(340, 190, 280, 100);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OPCIONES PARA PACIENTES: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 50, 360, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiosPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiosPacientesActionPerformed
        hacerClickOscuro(btnCambiosPacientes);
        IFCambiosPacientes.setVisible(true);
        IFCambiosPacientes.toFront(); 
        IFCambiosPacientes.refrescarTabla();
    }//GEN-LAST:event_btnCambiosPacientesActionPerformed

    private void btnAltasPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltasPacienteActionPerformed
        hacerClickOscuro(btnAltasPaciente);
        IFAltasPacientes.setVisible(true); 
        IFAltasPacientes.toFront();
        IFAltasPacientes.refrescarTabla();

    }//GEN-LAST:event_btnAltasPacienteActionPerformed

    private void btnBajasPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajasPacientesActionPerformed
        hacerClickOscuro(btnBajasPacientes);
        IFBajasPacientes.setVisible(true);
        IFBajasPacientes.toFront();
        IFBajasPacientes.refrescarTabla();

    }//GEN-LAST:event_btnBajasPacientesActionPerformed

    private void btnConsultasPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasPacientesActionPerformed
        hacerClickOscuro(btnConsultasPacientes);
        IFConsultasPacientes.setVisible(true); 
        IFConsultasPacientes.toFront(); 
        IFConsultasPacientes.refrescarTabla();
    }//GEN-LAST:event_btnConsultasPacientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltasPaciente;
    private javax.swing.JButton btnBajasPacientes;
    private javax.swing.JButton btnCambiosPacientes;
    private javax.swing.JButton btnConsultasPacientes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
