/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.JButton;

import javax.swing.Timer;

/**
 *
 * @author josesanchez
 */
public class InternalMedicos extends javax.swing.JInternalFrame {
    
    private InternalAltasMedicos IFAltasMedicos;
    private InternalBajasMedicos IFBajasMedicos; 
    private InternalConsultasMedicos IFConsultasMedicos;
    private InternalCambiosMedicos IFCambiosMedicos; 
    
  
    /**
     * Creates new form internalMedicos
     */
    public InternalMedicos(InternalAltasMedicos altasFrame, InternalBajasMedicos bajasFrame, InternalConsultasMedicos consultasMedicos, InternalCambiosMedicos cambiosMedicos) {
        this.IFAltasMedicos = altasFrame;
        this.IFBajasMedicos = bajasFrame; 
        this.IFConsultasMedicos = consultasMedicos; 
        this.IFCambiosMedicos = cambiosMedicos; 
        
        
        initComponents();
        setSize(700, 700);        
        setResizable(false);
      
        
        
        prepararBoton(btnAltasMedico);
        prepararBoton(btnBajasMedico);
        prepararBoton(btnConsultasMedico);
        prepararBoton(btnCambiosMedico);
        
        
        
    }
    
    
//============ METODOS DISENO BOTONES *START* ================ 
private void hacerClickOscuro(JButton boton) {

    // Color original guardado en una variable local
    Color original = boton.getBackground();

    // Color más oscuro
    Color oscuro = original.darker();

    boton.setBackground(oscuro);

    // Regresar al color original después de 150 ms
    Timer t = new Timer(150, e -> {
        boton.setBackground(original);
    });

    t.setRepeats(false);
    t.start();
}

private void prepararBoton(JButton boton) {
    boton.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    boton.setContentAreaFilled(true);
    boton.setOpaque(true);
    boton.setBorderPainted(false);
}
//=========== METODOS DISENO BOTONES *END* ============= 
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCambiosMedico = new javax.swing.JButton();
        btnAltasMedico = new javax.swing.JButton();
        btnBajasMedico = new javax.swing.JButton();
        btnConsultasMedico = new javax.swing.JButton();
        jScrollMedicos = new javax.swing.JScrollPane();
        tablaMedicos = new javax.swing.JTable();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Medicos");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setNormalBounds(new java.awt.Rectangle(0, 0, 700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setSize(new java.awt.Dimension(700, 700));
        setVisible(true);
        getContentPane().setLayout(null);

        btnCambiosMedico.setBackground(new java.awt.Color(100, 0, 0));
        btnCambiosMedico.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCambiosMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiosMedico.setText("Modificar");
        btnCambiosMedico.setBorder(null);
        btnCambiosMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiosMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiosMedico);
        btnCambiosMedico.setBounds(50, 160, 270, 100);

        btnAltasMedico.setBackground(new java.awt.Color(100, 0, 0));
        btnAltasMedico.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAltasMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnAltasMedico.setText("Agregar");
        btnAltasMedico.setBorder(null);
        btnAltasMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltasMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltasMedico);
        btnAltasMedico.setBounds(50, 40, 270, 100);

        btnBajasMedico.setBackground(new java.awt.Color(100, 0, 0));
        btnBajasMedico.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnBajasMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnBajasMedico.setText("Eliminar");
        btnBajasMedico.setBorder(null);
        btnBajasMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajasMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBajasMedico);
        btnBajasMedico.setBounds(340, 160, 280, 100);

        btnConsultasMedico.setBackground(new java.awt.Color(100, 0, 0));
        btnConsultasMedico.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnConsultasMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultasMedico.setText("Consultar");
        btnConsultasMedico.setBorder(null);
        btnConsultasMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultasMedico);
        btnConsultasMedico.setBounds(340, 40, 280, 100);

        jScrollMedicos.setBackground(new java.awt.Color(140, 59, 59));
        jScrollMedicos.setBorder(null);
        jScrollMedicos.setForeground(new java.awt.Color(255, 255, 255));

        tablaMedicos.setBackground(new java.awt.Color(100, 0, 0));
        tablaMedicos.setForeground(new java.awt.Color(255, 255, 255));
        tablaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Médico", "Nombre", "Apellido", "Departamento", "Dirección", "Teléfono"
            }
        ));
        jScrollMedicos.setViewportView(tablaMedicos);

        getContentPane().add(jScrollMedicos);
        jScrollMedicos.setBounds(30, 320, 610, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiosMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiosMedicoActionPerformed
        hacerClickOscuro(btnCambiosMedico);
        IFCambiosMedicos.setVisible(true);
        IFCambiosMedicos.toFront();
    }//GEN-LAST:event_btnCambiosMedicoActionPerformed

    private void btnAltasMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltasMedicoActionPerformed
        hacerClickOscuro(btnAltasMedico);
        IFAltasMedicos.setVisible(true);
        IFAltasMedicos.toFront();

    }//GEN-LAST:event_btnAltasMedicoActionPerformed

    private void btnBajasMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajasMedicoActionPerformed
        hacerClickOscuro(btnBajasMedico);
        IFBajasMedicos.setVisible(true);
        IFBajasMedicos.toFront();

    }//GEN-LAST:event_btnBajasMedicoActionPerformed

    private void btnConsultasMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasMedicoActionPerformed
        hacerClickOscuro(btnConsultasMedico);
        IFConsultasMedicos.setVisible(true);
        IFConsultasMedicos.toFront();
        
        
    }//GEN-LAST:event_btnConsultasMedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltasMedico;
    private javax.swing.JButton btnBajasMedico;
    private javax.swing.JButton btnCambiosMedico;
    private javax.swing.JButton btnConsultasMedico;
    private javax.swing.JScrollPane jScrollMedicos;
    private javax.swing.JTable tablaMedicos;
    // End of variables declaration//GEN-END:variables
}
