package vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class InternalAltasPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltasMedicos
     */
    public InternalAltasPacientes() {
        initComponents();
        setSize(700, 350);        
        setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarMedicoAltas = new javax.swing.JButton();
        btnRestablecerMedicoAltas1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 700, 350));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setPreferredSize(new java.awt.Dimension(700, 350));
        getContentPane().setLayout(null);

        btnAgregarMedicoAltas.setBackground(new java.awt.Color(120, 0, 0));
        btnAgregarMedicoAltas.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/WellmeadowsHospitalProyectoFinal/src/main/resources/Imagenes/add.png")); // NOI18N
        btnAgregarMedicoAltas.setToolTipText("Agregar");
        btnAgregarMedicoAltas.setBorder(null);
        btnAgregarMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarMedicoAltas);
        btnAgregarMedicoAltas.setBounds(460, 20, 50, 50);

        btnRestablecerMedicoAltas1.setBackground(new java.awt.Color(120, 0, 0));
        btnRestablecerMedicoAltas1.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/WellmeadowsHospitalProyectoFinal/src/main/resources/Imagenes/clean.png")); // NOI18N
        btnRestablecerMedicoAltas1.setToolTipText("Restablecer");
        btnRestablecerMedicoAltas1.setBorder(null);
        btnRestablecerMedicoAltas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedicoAltas1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestablecerMedicoAltas1);
        btnRestablecerMedicoAltas1.setBounds(460, 90, 50, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedicoAltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMedicoAltasActionPerformed

    private void btnRestablecerMedicoAltas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedicoAltas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestablecerMedicoAltas1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMedicoAltas;
    private javax.swing.JButton btnRestablecerMedicoAltas1;
    // End of variables declaration//GEN-END:variables
}
