/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.ButtonGroup;

/**
 *
 * @author josesanchez
 */
public class InternalConsultasPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltasPacientes
     */
    public InternalConsultasPacientes() {
        initComponents();
        setSize(700, 350);        
        setResizable(false);
        
        ButtonGroup group = new ButtonGroup();
        group.add(jRadioButton1); 
        group.add(jRadioButton2); 
        group.add(jRadioButton3);
        group.add(jRadioButton4); 
        group.add(jRadioButton5);
        group.add(jRadioButton6);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNombrePacientesConsultas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoIDPacienteConsultas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoTelefonoPacientesConsultas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoApellidoPacientesConsultas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboDiaRegistroConsultas = new javax.swing.JComboBox<>();
        comboMesRegistroConsultas = new javax.swing.JComboBox<>();
        comboAnoRegistroConsultas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboSexoConsultas = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboCivilConsultas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboDiaNacConsultas = new javax.swing.JComboBox<>();
        comboMesNacConsultas = new javax.swing.JComboBox<>();
        comboAnoNacConsultas = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        campoIdMedicoConsultas = new javax.swing.JTextField();
        btnRestablecerPacientesConsultas = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Agregar Pacientes");
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id Paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 80, 20);

        campoNombrePacientesConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombrePacientesConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(campoNombrePacientesConsultas);
        campoNombrePacientesConsultas.setBounds(170, 40, 380, 23);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 40, 70, 20);

        campoIDPacienteConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDPacienteConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(campoIDPacienteConsultas);
        campoIDPacienteConsultas.setBounds(170, 10, 380, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 70, 70, 17);

        campoTelefonoPacientesConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefonoPacientesConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(campoTelefonoPacientesConsultas);
        campoTelefonoPacientesConsultas.setBounds(170, 100, 380, 23);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefóno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 100, 60, 20);
        getContentPane().add(campoApellidoPacientesConsultas);
        campoApellidoPacientesConsultas.setBounds(170, 70, 380, 23);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 130, 160, 20);

        comboDiaRegistroConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(comboDiaRegistroConsultas);
        comboDiaRegistroConsultas.setBounds(210, 220, 72, 23);

        comboMesRegistroConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(comboMesRegistroConsultas);
        comboMesRegistroConsultas.setBounds(300, 220, 72, 23);

        comboAnoRegistroConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        getContentPane().add(comboAnoRegistroConsultas);
        comboAnoRegistroConsultas.setBounds(390, 220, 130, 23);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sexo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 160, 40, 20);

        comboSexoConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        getContentPane().add(comboSexoConsultas);
        comboSexoConsultas.setBounds(140, 160, 72, 23);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado Civil");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 190, 90, 20);

        comboCivilConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Separado", "Viudo" }));
        getContentPane().add(comboCivilConsultas);
        comboCivilConsultas.setBounds(180, 190, 97, 23);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de Registro");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 220, 120, 20);

        comboDiaNacConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(comboDiaNacConsultas);
        comboDiaNacConsultas.setBounds(240, 130, 72, 23);

        comboMesNacConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(comboMesNacConsultas);
        comboMesNacConsultas.setBounds(330, 130, 72, 23);

        comboAnoNacConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        getContentPane().add(comboAnoNacConsultas);
        comboAnoNacConsultas.setBounds(420, 130, 130, 23);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID del Médico de Cabecera");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 250, 180, 17);
        getContentPane().add(campoIdMedicoConsultas);
        campoIdMedicoConsultas.setBounds(260, 250, 290, 23);

        btnRestablecerPacientesConsultas.setText("Restablecer");
        getContentPane().add(btnRestablecerPacientesConsultas);
        btnRestablecerPacientesConsultas.setBounds(580, 40, 100, 23);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(40, 10, 30, 21);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(40, 40, 30, 21);
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(40, 70, 30, 21);
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(40, 100, 30, 21);
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(40, 130, 30, 21);
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(40, 160, 30, 21);
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(40, 190, 30, 21);
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(40, 220, 30, 21);
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(40, 250, 30, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombrePacientesConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombrePacientesConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombrePacientesConsultasActionPerformed

    private void campoIDPacienteConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDPacienteConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDPacienteConsultasActionPerformed

    private void campoTelefonoPacientesConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefonoPacientesConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoPacientesConsultasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestablecerPacientesConsultas;
    private javax.swing.JTextField campoApellidoPacientesConsultas;
    private javax.swing.JTextField campoIDPacienteConsultas;
    private javax.swing.JTextField campoIdMedicoConsultas;
    private javax.swing.JTextField campoNombrePacientesConsultas;
    private javax.swing.JTextField campoTelefonoPacientesConsultas;
    private javax.swing.JComboBox<String> comboAnoNacConsultas;
    private javax.swing.JComboBox<String> comboAnoRegistroConsultas;
    private javax.swing.JComboBox<String> comboCivilConsultas;
    private javax.swing.JComboBox<String> comboDiaNacConsultas;
    private javax.swing.JComboBox<String> comboDiaRegistroConsultas;
    private javax.swing.JComboBox<String> comboMesNacConsultas;
    private javax.swing.JComboBox<String> comboMesRegistroConsultas;
    private javax.swing.JComboBox<String> comboSexoConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables

    
}
