package vista;

import controlador.MedicoDAO;
import javax.swing.JOptionPane;
import modelo.Medico;
import modelo.ResultSetTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class InternalAltasMedicos extends javax.swing.JInternalFrame {
    
    
    private ResultSetTableModel modelo;
    private String driver = "org.postgresql.Driver";
    private String url = "jdbc:postgresql://localhost:5432/wellmeadows_hospital";
    /**
     * Creates new form InternalAltasMedicos
     */
    public InternalAltasMedicos() {
        initComponents();
        setSize(700, 700);        
        setResizable(false);
        cargarTodosLosMedicos(tablaAltasMedicos);
        
        
    }
    
    
    private void cargarTodosLosMedicos(javax.swing.JTable tablaMedicos) {
        try {
            String sql = "SELECT id_medico, nombre, apellido, numero_departamento, direccion, telefono FROM medicos_cabecera";
            modelo = new ResultSetTableModel(driver, url, sql);
            tablaMedicos.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
  
    
    
    
    private void restablecerCampos() {
        try {
       
            campoIdMedicoAltas.setText("");
            campoNombreMedicoAltas.setText("");
            campoApellidoMedicoAltas.setText("");
            campoDireccionMedicoAltas.setText("");
            campoNumTelefonoMedicosAltas.setText("");
            comboMedicoDepartamentoAtlas.setSelectedIndex(0);
            cargarTodosLosMedicos(tablaAltasMedicos);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void refrescarTabla(){
        cargarTodosLosMedicos(tablaAltasMedicos); 
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoIdMedicoAltas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoNombreMedicoAltas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoApellidoMedicoAltas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboMedicoDepartamentoAtlas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        campoDireccionMedicoAltas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoNumTelefonoMedicosAltas = new javax.swing.JTextField();
        btnAgregarMedicoAltas = new javax.swing.JButton();
        btnRestablecerMedicoAltas1 = new javax.swing.JButton();
        jScrollMedicos = new javax.swing.JScrollPane();
        tablaAltasMedicos = new javax.swing.JTable();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Agregar Medico");
        setToolTipText("");
        setBounds(new java.awt.Rectangle(0, 0, 700, 350));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setPreferredSize(new java.awt.Dimension(700, 350));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(110, 46, 46));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id del Médico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 90, 20);

        campoIdMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(campoIdMedicoAltas);
        campoIdMedicoAltas.setBounds(150, 20, 250, 20);

        jLabel2.setBackground(new java.awt.Color(110, 46, 46));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 60, 60, 20);

        campoNombreMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(campoNombreMedicoAltas);
        campoNombreMedicoAltas.setBounds(150, 60, 250, 20);

        jLabel3.setBackground(new java.awt.Color(110, 46, 46));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 100, 60, 20);

        campoApellidoMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(campoApellidoMedicoAltas);
        campoApellidoMedicoAltas.setBounds(150, 100, 250, 20);

        jLabel4.setBackground(new java.awt.Color(110, 46, 46));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número del Departamento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 180, 20);

        comboMedicoDepartamentoAtlas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));
        comboMedicoDepartamentoAtlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicoDepartamentoAtlasActionPerformed(evt);
            }
        });
        getContentPane().add(comboMedicoDepartamentoAtlas);
        comboMedicoDepartamentoAtlas.setBounds(230, 140, 72, 23);

        jLabel5.setBackground(new java.awt.Color(110, 46, 46));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 180, 70, 20);

        campoDireccionMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(campoDireccionMedicoAltas);
        campoDireccionMedicoAltas.setBounds(150, 180, 420, 20);

        jLabel6.setBackground(new java.awt.Color(110, 46, 46));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefóno");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 220, 70, 20);

        campoNumTelefonoMedicosAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumTelefonoMedicosAltasActionPerformed(evt);
            }
        });
        getContentPane().add(campoNumTelefonoMedicosAltas);
        campoNumTelefonoMedicosAltas.setBounds(150, 220, 420, 20);

        btnAgregarMedicoAltas.setText("Agregar");
        btnAgregarMedicoAltas.setToolTipText("Agrega la información del médico");
        btnAgregarMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarMedicoAltas);
        btnAgregarMedicoAltas.setBounds(470, 30, 110, 30);

        btnRestablecerMedicoAltas1.setText("Restablecer");
        btnRestablecerMedicoAltas1.setToolTipText("Limpia los Campos");
        btnRestablecerMedicoAltas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedicoAltas1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestablecerMedicoAltas1);
        btnRestablecerMedicoAltas1.setBounds(470, 70, 110, 30);

        jScrollMedicos.setBackground(new java.awt.Color(51, 0, 0));
        jScrollMedicos.setBorder(null);
        jScrollMedicos.setForeground(new java.awt.Color(51, 51, 51));

        tablaAltasMedicos.setBackground(new java.awt.Color(100, 0, 0));
        tablaAltasMedicos.setForeground(new java.awt.Color(255, 255, 255));
        tablaAltasMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Médico", "Nombre", "Apellido", "Departamento", "Dirección", "Teléfono"
            }
        ));
        jScrollMedicos.setViewportView(tablaAltasMedicos);

        getContentPane().add(jScrollMedicos);
        jScrollMedicos.setBounds(30, 290, 610, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdMedicoAltasActionPerformed
        
    }//GEN-LAST:event_campoIdMedicoAltasActionPerformed

    private void campoNombreMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreMedicoAltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreMedicoAltasActionPerformed

    private void campoApellidoMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoMedicoAltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoMedicoAltasActionPerformed

    private void comboMedicoDepartamentoAtlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicoDepartamentoAtlasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMedicoDepartamentoAtlasActionPerformed

    private void campoDireccionMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionMedicoAltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionMedicoAltasActionPerformed

    private void campoNumTelefonoMedicosAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumTelefonoMedicosAltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumTelefonoMedicosAltasActionPerformed

    private void btnAgregarMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedicoAltasActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(campoIdMedicoAltas.getText().trim()); 
            String nombre = campoNombreMedicoAltas.getText().trim(); 
            String apellido = campoApellidoMedicoAltas.getText().trim(); 
            int numDept = Integer.parseInt(comboMedicoDepartamentoAtlas.getSelectedItem().toString()); 
            String direccion = campoDireccionMedicoAltas.getText().trim(); 
            String telefono = campoNumTelefonoMedicosAltas.getText().trim(); 
            
            if(nombre.isEmpty() || apellido.isEmpty() || direccion.isEmpty() || telefono.isEmpty()){
                JOptionPane.showMessageDialog(this, "Porfavor acomplete todos los campos");
                return; 
            }
            
            Medico m = new Medico(); 
            m.setIdMedico(id); 
            m.setNombre(nombre); 
            m.setApellido(apellido); 
            m.setNumeroDepartamento(numDept); 
            m.setDireccion(direccion); 
            m.setTelefono(telefono);
            
            boolean ok = MedicoDAO.getInstancia().agregarMedico(m); 
            if(ok){
                JOptionPane.showMessageDialog(this, "Médico registrado exitosamente. RAAHH!!!");
                
                cargarTodosLosMedicos(tablaAltasMedicos);
                restablecerCampos();
            }else{
                JOptionPane.showMessageDialog(this, "No se puedo registrar el doc (ya existe)");
            }
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "ID o Número de Departamento Inválido");
        }
    }//GEN-LAST:event_btnAgregarMedicoAltasActionPerformed
    
    
    private void btnRestablecerMedicoAltas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedicoAltas1ActionPerformed
        // TODO add your handling code here:
        
        
        restablecerCampos();
    }//GEN-LAST:event_btnRestablecerMedicoAltas1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMedicoAltas;
    private javax.swing.JButton btnRestablecerMedicoAltas1;
    private javax.swing.JTextField campoApellidoMedicoAltas;
    private javax.swing.JTextField campoDireccionMedicoAltas;
    private javax.swing.JTextField campoIdMedicoAltas;
    private javax.swing.JTextField campoNombreMedicoAltas;
    private javax.swing.JTextField campoNumTelefonoMedicosAltas;
    private javax.swing.JComboBox<String> comboMedicoDepartamentoAtlas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollMedicos;
    private javax.swing.JTable tablaAltasMedicos;
    // End of variables declaration//GEN-END:variables
}
