package vista;

import javax.swing.ButtonGroup;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class InternalConsultasMedicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltasMedicos
     */
    public InternalConsultasMedicos() {
        initComponents();
        setSize(700, 350);        
        setResizable(false);
        
        ButtonGroup group = new ButtonGroup();
        group.add(jRadioButton1); 
        group.add(jRadioButton2); 
        group.add(jRadioButton3);
        group.add(jRadioButton4); 
        group.add(jRadioButton5);
        group.add(jRadioButton6);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        campoIdMedicoConsultas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        campoNombreMedicoConsultas = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        campoApellidoMedicoConsultas = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        comboMedicoDepartamentoConsultas = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        campoDireccionMedicoConsultas = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        campoDireccionMedicoAltas5 = new javax.swing.JTextField();
        btnRestablecerMedicosConsultas = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 700, 350));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setPreferredSize(new java.awt.Dimension(700, 350));
        getContentPane().setLayout(null);

        jLabel17.setBackground(new java.awt.Color(110, 46, 46));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Id del Médico");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(70, 10, 90, 20);

        campoIdMedicoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdMedicoConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(campoIdMedicoConsultas);
        campoIdMedicoConsultas.setBounds(190, 10, 220, 20);

        jLabel18.setBackground(new java.awt.Color(110, 46, 46));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nombre");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(70, 50, 60, 20);

        campoNombreMedicoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreMedicoConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(campoNombreMedicoConsultas);
        campoNombreMedicoConsultas.setBounds(150, 50, 260, 20);

        jLabel19.setBackground(new java.awt.Color(110, 46, 46));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Apellido");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(70, 90, 60, 20);

        campoApellidoMedicoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoMedicoConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(campoApellidoMedicoConsultas);
        campoApellidoMedicoConsultas.setBounds(150, 90, 260, 20);

        jLabel20.setBackground(new java.awt.Color(110, 46, 46));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Número del Departamento");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(70, 130, 180, 20);

        comboMedicoDepartamentoConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));
        comboMedicoDepartamentoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicoDepartamentoConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(comboMedicoDepartamentoConsultas);
        comboMedicoDepartamentoConsultas.setBounds(260, 130, 72, 23);

        jLabel21.setBackground(new java.awt.Color(110, 46, 46));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Dirección");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(70, 170, 70, 20);

        campoDireccionMedicoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionMedicoConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(campoDireccionMedicoConsultas);
        campoDireccionMedicoConsultas.setBounds(160, 170, 370, 20);

        jLabel22.setBackground(new java.awt.Color(110, 46, 46));
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Telefóno");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(70, 210, 70, 20);

        campoDireccionMedicoAltas5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionMedicoAltas5ActionPerformed(evt);
            }
        });
        getContentPane().add(campoDireccionMedicoAltas5);
        campoDireccionMedicoAltas5.setBounds(150, 210, 380, 20);

        btnRestablecerMedicosConsultas.setBackground(new java.awt.Color(91, 4, 4));
        btnRestablecerMedicosConsultas.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/WellmeadowsHospitalProyectoFinal/src/main/resources/Imagenes/clean.png")); // NOI18N
        btnRestablecerMedicosConsultas.setToolTipText("Restablecer");
        btnRestablecerMedicosConsultas.setBorder(null);
        btnRestablecerMedicosConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedicosConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestablecerMedicosConsultas);
        btnRestablecerMedicosConsultas.setBounds(480, 20, 50, 50);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(30, 10, 30, 20);

        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(30, 50, 30, 19);

        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(30, 90, 30, 20);

        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(30, 130, 30, 19);

        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(30, 170, 30, 20);

        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(30, 210, 30, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdMedicoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdMedicoConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdMedicoConsultasActionPerformed

    private void campoNombreMedicoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreMedicoConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreMedicoConsultasActionPerformed

    private void campoApellidoMedicoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoMedicoConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoMedicoConsultasActionPerformed

    private void comboMedicoDepartamentoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicoDepartamentoConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMedicoDepartamentoConsultasActionPerformed

    private void campoDireccionMedicoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionMedicoConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionMedicoConsultasActionPerformed

    private void campoDireccionMedicoAltas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionMedicoAltas5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionMedicoAltas5ActionPerformed

    private void btnRestablecerMedicosConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedicosConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestablecerMedicosConsultasActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestablecerMedicosConsultas;
    private javax.swing.JTextField campoApellidoMedicoConsultas;
    private javax.swing.JTextField campoDireccionMedicoAltas5;
    private javax.swing.JTextField campoDireccionMedicoConsultas;
    private javax.swing.JTextField campoIdMedicoConsultas;
    private javax.swing.JTextField campoNombreMedicoConsultas;
    private javax.swing.JComboBox<String> comboMedicoDepartamentoConsultas;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    // End of variables declaration//GEN-END:variables
}
