package vista;

import controlador.MedicoDAO;
import javax.swing.JOptionPane;
import modelo.ResultSetTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class InternalBajasMedicos extends javax.swing.JInternalFrame {
    private ResultSetTableModel modelo;
    private String driver = "org.postgresql.Driver";
    private String url = "jdbc:postgresql://localhost:5432/wellmeadows_hospital";
    /**
     * Creates new form InternalAltasMedicos
     */    
    public InternalBajasMedicos() {
        initComponents();
        setSize(700, 700);        
        setResizable(false);
        
        cargarTodosLosMedicos(tablaBajasMedicos);
        
        campoIdMedicoBajas.addKeyListener(new java.awt.event.KeyAdapter(){
            @Override
            public void keyReleased(java.awt.event.KeyEvent e){
                String texto = campoIdMedicoBajas.getText().trim(); 
            
                if(texto.isEmpty()){
                    cargarTodosLosMedicos(tablaBajasMedicos); 
                
                }else{
                    filtrar(tablaBajasMedicos, texto);
                }
            }   
        }); 
        
       
    }
    
    private void cargarTodosLosMedicos(javax.swing.JTable tablaMedicos) {
        try {
            String sql = "SELECT id_medico, nombre, apellido, numero_departamento, direccion, telefono FROM medicos_cabecera";
            modelo = new ResultSetTableModel(driver, url, sql);
            tablaMedicos.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
  
    
    
    
    private void restablecerCampos() {
        try {
       
            campoIdMedicoBajas.setText("");
            cargarTodosLosMedicos(tablaBajasMedicos);


        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void filtrar(javax.swing.JTable tabla, String id){
        try{
            String sql = "SELECT id_medico, nombre, apellido, numero_departamento, direccion, telefono "+
                    "FROM medicos_cabecera " + "WHERE CAST(id_medico AS TEXT) ILIKE '%" + id + "%'"; 
            modelo = new ResultSetTableModel(driver, url, sql); 
            tabla.setModel(modelo);
            
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    
    
    public void refrescarTabla(){
        cargarTodosLosMedicos(tablaBajasMedicos);
    }
    
    public void soloNumeros(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != '\b') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten números!");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        campoIdMedicoBajas = new javax.swing.JTextField();
        btnElminarMedicoAltas = new javax.swing.JButton();
        btnRestablecerMedicosBajas = new javax.swing.JButton();
        jScrollMedicos = new javax.swing.JScrollPane();
        tablaBajasMedicos = new javax.swing.JTable();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 700, 350));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setPreferredSize(new java.awt.Dimension(700, 350));
        getContentPane().setLayout(null);

        jLabel8.setBackground(new java.awt.Color(110, 46, 46));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id del Médico");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 40, 90, 20);

        campoIdMedicoBajas.setToolTipText("Campo para eliminar.");
        campoIdMedicoBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdMedicoBajasActionPerformed(evt);
            }
        });
        campoIdMedicoBajas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIdMedicoBajasKeyTyped(evt);
            }
        });
        getContentPane().add(campoIdMedicoBajas);
        campoIdMedicoBajas.setBounds(170, 40, 420, 20);

        btnElminarMedicoAltas.setText("Eliminar");
        btnElminarMedicoAltas.setToolTipText("Elimina el médico que se indicó en el campo del ID");
        btnElminarMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElminarMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(btnElminarMedicoAltas);
        btnElminarMedicoAltas.setBounds(340, 100, 250, 40);

        btnRestablecerMedicosBajas.setText("Restablecer");
        btnRestablecerMedicosBajas.setToolTipText("Restablece los campos a su forma original");
        btnRestablecerMedicosBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedicosBajasActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestablecerMedicosBajas);
        btnRestablecerMedicosBajas.setBounds(60, 100, 260, 40);

        jScrollMedicos.setBackground(new java.awt.Color(51, 0, 0));
        jScrollMedicos.setBorder(null);
        jScrollMedicos.setForeground(new java.awt.Color(51, 51, 51));

        tablaBajasMedicos.setBackground(new java.awt.Color(100, 0, 0));
        tablaBajasMedicos.setForeground(new java.awt.Color(255, 255, 255));
        tablaBajasMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Médico", "Nombre", "Apellido", "Departamento", "Dirección", "Teléfono"
            }
        ));
        jScrollMedicos.setViewportView(tablaBajasMedicos);

        getContentPane().add(jScrollMedicos);
        jScrollMedicos.setBounds(30, 230, 610, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdMedicoBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdMedicoBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdMedicoBajasActionPerformed

    private void btnElminarMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElminarMedicoAltasActionPerformed
        // TODO add your handling code here:
        if(campoIdMedicoBajas.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "No se puede eliminar sin un id.");
            return; 
        }
        
        
        
        int id = Integer.parseInt(campoIdMedicoBajas.getText().trim()); 
        
        Progreso dialogProgreso = new Progreso(null, true);
	dialogProgreso.setTitle("Procesando...");
    
    	Thread t = new Thread(() -> {
        	try {
            	for (int i = 0; i <= 100; i += 10) {
                	dialogProgreso.setProgreso(i);
                	Thread.sleep(150); 
            	}
       	} catch (Exception e) {
        	} finally {
            dialogProgreso.finalizar();
        }
    	});

    	t.start();
    	dialogProgreso.iniciar();
        
        
        boolean eliminado = MedicoDAO.getInstancia().eliminarMedico(id); 
        
        if(eliminado){
            JOptionPane.showMessageDialog(this, "Médico se eliminó exitosamente junto a todos sus pacientes (CASCADE).");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo eliminar al doc. Favor de Verificar el ID!");
        }
        
        cargarTodosLosMedicos(tablaBajasMedicos);
        restablecerCampos();



    }//GEN-LAST:event_btnElminarMedicoAltasActionPerformed

    private void btnRestablecerMedicosBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedicosBajasActionPerformed
        // TODO add your handling code here:
        restablecerCampos();
    }//GEN-LAST:event_btnRestablecerMedicosBajasActionPerformed

    private void campoIdMedicoBajasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdMedicoBajasKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_campoIdMedicoBajasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElminarMedicoAltas;
    private javax.swing.JButton btnRestablecerMedicosBajas;
    private javax.swing.JTextField campoIdMedicoBajas;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollMedicos;
    private javax.swing.JTable tablaBajasMedicos;
    // End of variables declaration//GEN-END:variables
}
