/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.JButton;

import javax.swing.Timer;


/**
 *
 * @author josesanchez
 */
//[[[[[[[[[[[[[[[[[[[[[[[[[[[ SOLID ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
// CUMPLE CON SINGLE RESPONSABILITY PORQUE ESTA CLASE SOLO TIENE UNA RESPONSABILIDAD.
// CIMPLE CON DEPENDENCY INVERSION porque no depende de implementaciones, depende solo de abstracciones
// CUMPLE CON INTERFACE SEGREGATION porque su unico proposito es los botones y no se ve forzado ser
//dependiente de una interfaz, ni interfazes tiene. 

public class InternalVistas extends javax.swing.JInternalFrame {
    private InternalVistas1 IFVistas1; 
    private InternalTabla2 IFVistas2; 
    private InternalTabla3 IFVistas3; 
    /**
     * Creates new form internalMedicos
     */
    public InternalVistas(InternalVistas1 IFVistas, InternalTabla2 IFVistas2, InternalTabla3 IFVistas3) {
         this.IFVistas1 = IFVistas; 
         this.IFVistas2 = IFVistas2; 
         this.IFVistas3 = IFVistas3;
         
        initComponents();
        setSize(500, 700);        
        setResizable(false);

        prepararBoton(btnVista1);
        prepararBoton(btnVista3);
        prepararBoton(btnVista2);
        
        
        
    }
    
    
    
//============ METODOS DISENO BOTONES *START* ================ 
private void hacerClickOscuro(JButton boton) {

    // Color original guardado en una variable local
    Color original = boton.getBackground();

    // Color más oscuro
    Color oscuro = original.darker();

    boton.setBackground(oscuro);

    // Regresar al color original después de 150 ms
    Timer t = new Timer(150, e -> {
        boton.setBackground(original);
    });

    t.setRepeats(false);
    t.start();
}

private void prepararBoton(JButton boton) {
    boton.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    boton.setContentAreaFilled(true);
    boton.setOpaque(true);
    boton.setBorderPainted(false);
}
//=========== METODOS DISENO BOTONES *END* ============= 
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVista2 = new javax.swing.JButton();
        btnVista1 = new javax.swing.JButton();
        btnVista3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Información");
        setToolTipText("");
        setBounds(new java.awt.Rectangle(100, 0, 700, 700));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setNormalBounds(new java.awt.Rectangle(0, 0, 700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setVisible(true);
        getContentPane().setLayout(null);

        btnVista2.setBackground(new java.awt.Color(100, 0, 0));
        btnVista2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnVista2.setForeground(new java.awt.Color(255, 255, 255));
        btnVista2.setText("Historial Médicos");
        btnVista2.setToolTipText("");
        btnVista2.setBorder(null);
        btnVista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVista2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVista2);
        btnVista2.setBounds(100, 200, 270, 80);

        btnVista1.setBackground(new java.awt.Color(100, 0, 0));
        btnVista1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnVista1.setForeground(new java.awt.Color(255, 255, 255));
        btnVista1.setText("Vista Pacientes de Médicos");
        btnVista1.setBorder(null);
        btnVista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVista1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVista1);
        btnVista1.setBounds(100, 90, 270, 80);

        btnVista3.setBackground(new java.awt.Color(100, 0, 0));
        btnVista3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnVista3.setForeground(new java.awt.Color(255, 255, 255));
        btnVista3.setText("Historial Pacientes");
        btnVista3.setToolTipText("");
        btnVista3.setBorder(null);
        btnVista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVista3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVista3);
        btnVista3.setBounds(100, 310, 270, 80);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vistas Disponibles:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 230, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVista2ActionPerformed
        hacerClickOscuro(btnVista2);
        IFVistas2.setVisible(true); 
        IFVistas2.toFront();
        IFVistas2.cargarVista();
     
        
    }//GEN-LAST:event_btnVista2ActionPerformed

    private void btnVista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVista1ActionPerformed
        hacerClickOscuro(btnVista1);
        IFVistas1.setVisible(true);
        IFVistas1.toFront();
        IFVistas1.cargarVista();
        
        

    }//GEN-LAST:event_btnVista1ActionPerformed

    private void btnVista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVista3ActionPerformed
        hacerClickOscuro(btnVista3);
        IFVistas3.setVisible(true); 
        IFVistas3.toFront();
        IFVistas3.cargarVista();

    }//GEN-LAST:event_btnVista3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVista1;
    private javax.swing.JButton btnVista2;
    private javax.swing.JButton btnVista3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
