package vista;

import controlador.MedicoDAO;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class InternalBajasMedicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltasMedicos
     */
    public InternalBajasMedicos() {
        initComponents();
        setSize(700, 350);        
        setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        campoIdMedicoBajas = new javax.swing.JTextField();
        btnElminarMedicoAltas = new javax.swing.JButton();
        btnRestablecerMedicosBajas = new javax.swing.JButton();
        campoNombrePacientesBajas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoApellidoPacienteBajas = new javax.swing.JTextField();

        setBackground(new java.awt.Color(120, 0, 0));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 700, 350));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setPreferredSize(new java.awt.Dimension(700, 350));
        getContentPane().setLayout(null);

        jLabel8.setBackground(new java.awt.Color(110, 46, 46));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id del Médico");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 40, 90, 20);

        campoIdMedicoBajas.setToolTipText("Campo para eliminar.");
        campoIdMedicoBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdMedicoBajasActionPerformed(evt);
            }
        });
        getContentPane().add(campoIdMedicoBajas);
        campoIdMedicoBajas.setBounds(150, 40, 360, 20);

        btnElminarMedicoAltas.setText("Eliminar");
        btnElminarMedicoAltas.setToolTipText("Elimina el médico que se indicó en el campo del ID");
        btnElminarMedicoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElminarMedicoAltasActionPerformed(evt);
            }
        });
        getContentPane().add(btnElminarMedicoAltas);
        btnElminarMedicoAltas.setBounds(230, 170, 120, 40);

        btnRestablecerMedicosBajas.setText("Restablecer");
        btnRestablecerMedicosBajas.setToolTipText("Restablece los campos a su forma original");
        btnRestablecerMedicosBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerMedicosBajasActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestablecerMedicosBajas);
        btnRestablecerMedicosBajas.setBounds(380, 170, 120, 40);

        campoNombrePacientesBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombrePacientesBajasActionPerformed(evt);
            }
        });
        getContentPane().add(campoNombrePacientesBajas);
        campoNombrePacientesBajas.setBounds(150, 80, 360, 23);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 80, 70, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 70, 20);
        getContentPane().add(campoApellidoPacienteBajas);
        campoApellidoPacienteBajas.setBounds(150, 120, 360, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIdMedicoBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdMedicoBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdMedicoBajasActionPerformed

    private void btnElminarMedicoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElminarMedicoAltasActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(campoIdMedicoBajas.getText().trim()); 
        
        boolean eliminado = MedicoDAO.getInstancia().eliminarMedico(id); 
        
        if(eliminado){
            JOptionPane.showMessageDialog(this, "Médico se eliminó exitosamente.");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo eliminar al doc. Favor de Verificar el ID!");
        }
        
    }//GEN-LAST:event_btnElminarMedicoAltasActionPerformed

    private void btnRestablecerMedicosBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerMedicosBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestablecerMedicosBajasActionPerformed

    private void campoNombrePacientesBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombrePacientesBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombrePacientesBajasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElminarMedicoAltas;
    private javax.swing.JButton btnRestablecerMedicosBajas;
    private javax.swing.JTextField campoApellidoPacienteBajas;
    private javax.swing.JTextField campoIdMedicoBajas;
    private javax.swing.JTextField campoNombrePacientesBajas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
