/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author josesanchez
 */
public class VentanaInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicio.class.getName());

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        setSize(1000, 750);        
        setResizable(false); 
 
           System.out.println(getClass().getResource("/Imagenes/logo.png"));
        
          //cositas de diseño 
         
        
        ImageIcon iconoOriginal = new ImageIcon(
            getClass().getResource("/Imagenes/logo.png"));

        Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
            160,
            160,
            Image.SCALE_SMOOTH);

        Logotipo.setIcon(new ImageIcon(imagenEscalada));
        
        setLocationRelativeTo(null);
        setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoIzquierdo = new javax.swing.JPanel();
        Logotipo = new javax.swing.JLabel();
        panelFondoDerecho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelFondoIzquierdo.setBackground(new java.awt.Color(61, 4, 4));

        javax.swing.GroupLayout panelFondoIzquierdoLayout = new javax.swing.GroupLayout(panelFondoIzquierdo);
        panelFondoIzquierdo.setLayout(panelFondoIzquierdoLayout);
        panelFondoIzquierdoLayout.setHorizontalGroup(
            panelFondoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoIzquierdoLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(Logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        panelFondoIzquierdoLayout.setVerticalGroup(
            panelFondoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoIzquierdoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(587, Short.MAX_VALUE))
        );

        getContentPane().add(panelFondoIzquierdo);
        panelFondoIzquierdo.setBounds(0, 0, 230, 770);

        panelFondoDerecho.setBackground(new java.awt.Color(110, 46, 46));

        javax.swing.GroupLayout panelFondoDerechoLayout = new javax.swing.GroupLayout(panelFondoDerecho);
        panelFondoDerecho.setLayout(panelFondoDerechoLayout);
        panelFondoDerechoLayout.setHorizontalGroup(
            panelFondoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        panelFondoDerechoLayout.setVerticalGroup(
            panelFondoDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        getContentPane().add(panelFondoDerecho);
        panelFondoDerecho.setBounds(230, 0, 890, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logotipo;
    private javax.swing.JPanel panelFondoDerecho;
    private javax.swing.JPanel panelFondoIzquierdo;
    // End of variables declaration//GEN-END:variables
}
