/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.Timer;

/**
 *
 * @author josesanchez
 */
public class VentanaInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicio.class.getName());

    /**
     * Creates new form VentanaInicio
     */
    //internal iniciales
    
  
    InternalAltasMedicos IFAltasMedicos = new InternalAltasMedicos();
    InternalBajasMedicos IFBajasMedicos = new InternalBajasMedicos(); 
    InternalConsultasMedicos IFConsultasMedicos = new InternalConsultasMedicos();
    InternalCambiosMedicos IFCambiosMedicos = new InternalCambiosMedicos(); 
    InternalAltasPacientes IFAltasPacientes = new InternalAltasPacientes();
    InternalBajasPacientes IFBajasPacientes = new InternalBajasPacientes();
    InternalCambiosPacientes IFCambiosPacientes = new InternalCambiosPacientes();
    InternalConsultasPacientes IFConsultasPacientes = new InternalConsultasPacientes();
    InternalVistas1 IFVistas1 = new InternalVistas1(); 
    InternalTabla2 IFVistas2 = new InternalTabla2(); 
    InternalTabla3 IFVista3 = new InternalTabla3(); 
      
    
    
    InternalMedicos IFMedicos = new InternalMedicos( IFAltasMedicos, IFBajasMedicos, IFConsultasMedicos, IFCambiosMedicos); 
    InternalPacientes IFPacientes = new InternalPacientes(IFAltasPacientes, IFBajasPacientes, IFCambiosPacientes, IFConsultasPacientes); 
    InternalVistas IFVistas = new InternalVistas(IFVistas1, IFVistas2, IFVista3); 
    
    public VentanaInicio() {
        initComponents();
        setSize(1000, 800);        
        setResizable(false);
        
   
       
        //componentes necesarios
        prepararBoton(btnMedicos);
        prepararBoton(btnPacientes);
        prepararBoton(btnReporte);
        prepararBoton(btnVistas);
        prepararBoton(btnGrafica);
        
        //---- elementos JDesktopPane --------
        jDesktopPane1.add(IFMedicos);
        IFMedicos.setVisible(false);   // empieza oculto
        IFMedicos.setLocation(0, 0);
        
        
        jDesktopPane1.add(IFPacientes); 
        IFPacientes.setVisible(false); 
        IFMedicos.setLocation(0, 0);
        
        jDesktopPane1.add(IFAltasMedicos); 
        IFAltasMedicos.setVisible(false);
        IFAltasMedicos.setLocation(0, 0);
        
        jDesktopPane1.add(IFBajasMedicos); 
        IFBajasMedicos.setVisible(false);
        IFBajasMedicos.setLocation(0, 0);
        
        jDesktopPane1.add(IFCambiosMedicos); 
        IFCambiosMedicos.setVisible(false);
        IFCambiosMedicos.setLocation(0, 0); 
        
        jDesktopPane1.add(IFConsultasMedicos); 
        IFConsultasMedicos.setVisible(false);
        IFConsultasMedicos.setLocation(0, 0);
        
        jDesktopPane1.add(IFAltasPacientes);
        IFAltasPacientes.setVisible(false);
        IFAltasPacientes.setLocation(0, 0);
        
        jDesktopPane1.add(IFBajasPacientes); 
        IFBajasPacientes.setVisible(false);
        IFBajasPacientes.setLocation(0, 0); 
        
        jDesktopPane1.add(IFCambiosPacientes); 
        IFCambiosPacientes.setVisible(false);
        IFCambiosPacientes.setLocation(0, 0);
        
        jDesktopPane1.add(IFConsultasPacientes); 
        IFConsultasPacientes.setVisible(false); 
        IFConsultasPacientes.setLocation(0, 0);
       
        jDesktopPane1.add(IFVistas); 
        IFVistas.setVisible(false); 
        IFVistas.setLocation(0, 0);
        
        jDesktopPane1.add(IFVistas1); 
        IFVistas1.setVisible(false);
        IFVistas1.setLocation(0, 0);
        
        jDesktopPane1.add(IFVistas2); 
        IFVistas2.setVisible(false); 
        IFVistas2.setLocation(0, 0);
        
        
        jDesktopPane1.add(IFVista3); 
        IFVista3.setVisible(false); 
        IFVista3.setLocation(0, 0);
       
        
        
        
        //--- end elementos JDesktopPane ----- 
        
        
        //end componentes
        
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIzquierdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMedicos = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnVistas = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnGrafica = new javax.swing.JButton();
        panelDerecho = new javax.swing.JPanel();
        logoGrande = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wellmeadows Hospital");
        setBackground(new java.awt.Color(70, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 1000, 800));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setName("desktopWm"); // NOI18N
        getContentPane().setLayout(null);

        panelIzquierdo.setBackground(new java.awt.Color(70, 0, 0));
        panelIzquierdo.setBounds(new java.awt.Rectangle(0, 0, 200, 800));
        panelIzquierdo.setMaximumSize(new java.awt.Dimension(200, 800));
        panelIzquierdo.setPreferredSize(new java.awt.Dimension(200, 800));
        panelIzquierdo.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/WellmeadowsHospitalProyectoFinal/src/main/resources/Imagenes/logo.png")); // NOI18N
        panelIzquierdo.add(jLabel1);
        jLabel1.setBounds(20, 20, 160, 158);

        btnMedicos.setBackground(new java.awt.Color(90, 0, 0));
        btnMedicos.setForeground(new java.awt.Color(255, 255, 255));
        btnMedicos.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/WellmeadowsHospitalProyectoFinal/src/main/resources/medicoBtn.png")); // NOI18N
        btnMedicos.setText("Médicos");
        btnMedicos.setActionCommand("Médicos ");
        btnMedicos.setBorder(null);
        btnMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicosActionPerformed(evt);
            }
        });
        panelIzquierdo.add(btnMedicos);
        btnMedicos.setBounds(0, 220, 200, 80);

        btnPacientes.setBackground(new java.awt.Color(90, 0, 0));
        btnPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btnPacientes.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/ProjectoFinalWM_mock/src/main/resources/Imagenes/pacientBtn.png")); // NOI18N
        btnPacientes.setText("Pacientes");
        btnPacientes.setBorder(null);
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });
        panelIzquierdo.add(btnPacientes);
        btnPacientes.setBounds(0, 330, 200, 80);

        btnVistas.setBackground(new java.awt.Color(90, 0, 0));
        btnVistas.setForeground(new java.awt.Color(255, 255, 255));
        btnVistas.setText("Información");
        btnVistas.setActionCommand("GenerarPDF");
        btnVistas.setBorder(null);
        btnVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistasActionPerformed(evt);
            }
        });
        panelIzquierdo.add(btnVistas);
        btnVistas.setBounds(0, 440, 200, 80);

        btnReporte.setBackground(new java.awt.Color(90, 0, 0));
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setText("Generar Reporte");
        btnReporte.setToolTipText("");
        btnReporte.setActionCommand("GenerarGrafica");
        btnReporte.setBorder(null);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        panelIzquierdo.add(btnReporte);
        btnReporte.setBounds(0, 660, 200, 80);

        btnGrafica.setBackground(new java.awt.Color(90, 0, 0));
        btnGrafica.setForeground(new java.awt.Color(255, 255, 255));
        btnGrafica.setText("Generar Gráfica");
        btnGrafica.setActionCommand("GenerarGrafica");
        btnGrafica.setBorder(null);
        btnGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaActionPerformed(evt);
            }
        });
        panelIzquierdo.add(btnGrafica);
        btnGrafica.setBounds(0, 550, 200, 80);

        getContentPane().add(panelIzquierdo);
        panelIzquierdo.setBounds(0, 0, 200, 800);

        panelDerecho.setBackground(new java.awt.Color(120, 0, 0));
        panelDerecho.setBounds(new java.awt.Rectangle(200, 0, 800, 800));
        panelDerecho.setMaximumSize(new java.awt.Dimension(800, 800));
        panelDerecho.setLayout(null);

        logoGrande.setIcon(new javax.swing.ImageIcon("/Users/josesanchez/Desktop/PROYECTO FINAL/ProjectoFinalWM_mock/src/main/resources/Imagenes/WMlogo copy.png")); // NOI18N
        panelDerecho.add(logoGrande);
        logoGrande.setBounds(140, 130, 500, 510);

        jDesktopPane1.setBackground(new java.awt.Color(110, 0, 0));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(700, 700));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(700, 700));
        jDesktopPane1.setRequestFocusEnabled(false);
        panelDerecho.add(jDesktopPane1);
        jDesktopPane1.setBounds(50, 50, 700, 700);

        getContentPane().add(panelDerecho);
        panelDerecho.setBounds(200, 0, 800, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //-------------- métodos para la vista -------------------------
    

//============ METODOS DISENO BOTONES *START* ================ 
private void hacerClickOscuro(JButton boton) {

    // Color original guardado en una variable local
    Color original = boton.getBackground();

    // Color más oscuro
    Color oscuro = original.darker();

    boton.setBackground(oscuro);

    // Regresar al color original después de 150 ms
    Timer t = new Timer(150, e -> {
        boton.setBackground(original);
    });

    t.setRepeats(false);
    t.start();
}

private void prepararBoton(JButton boton) {
    boton.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    boton.setContentAreaFilled(true);
    boton.setOpaque(true);
    boton.setBorderPainted(false);
}
//=========== METODOS DISENO BOTONES *END* ============= 
    
    
    private void btnMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicosActionPerformed
        hacerClickOscuro(btnMedicos);
        IFMedicos.setVisible(true);
        IFMedicos.toFront();
        
    }//GEN-LAST:event_btnMedicosActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        hacerClickOscuro(btnPacientes);
        IFPacientes.setVisible(true);
        IFPacientes.toFront();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistasActionPerformed
        hacerClickOscuro(btnVistas);
        IFVistas.setVisible(true); 
        IFVistas.toFront();
    }//GEN-LAST:event_btnVistasActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        hacerClickOscuro(btnReporte);
        IFVistas1.generarReportePDF();
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaActionPerformed
        // TODO add your handling code here:
        hacerClickOscuro(btnGrafica);
        IFVistas1.generarGraficaTop2();
    }//GEN-LAST:event_btnGraficaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrafica;
    private javax.swing.JButton btnMedicos;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnVistas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoGrande;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelIzquierdo;
    // End of variables declaration//GEN-END:variables
}
